Skip to content
Search or jump to…
Pull requests
Issues
Marketplace
Explore
@Alexstuder
Alexstuder
/
climatedataanalyser
1
10
Code
Issues
Pull requests
Actions
Projects
Wiki
Security
Insights
Settings
climatedataanalyser/climatedataanalyser-api/src/main/resources/application.properties
@Alexstuder
Alexstuder Transfer Directory Disaster !
Latest commit 9f566a1 18 hours ago
History
1 contributor
90 lines (90 sloc)  3.77 KB
IntelliJ IDEAPhpStormWebStorm   
server.port=8092
spring.profiles.active=prod
# H2 DataBase Config
#spring.datasource.driver-class-name=org.h2.Driver
#spring.datasource.url=jdbc:h2:file:./climatedatabase.db;DB_CLOSE_DELAY=-1;MODE=MySQL
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#
##Don't init the DB after boot
##--> erkennt climatedatabase.db nicht !
##climatedatabase.db.recreate=false
#spring.jpa.hibernate.ddl-auto=validate
#
#spring.datasource.username=climateUser
#spring.datasource.password=climateUser
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=none
# MYSQL Config
spring.datasource.url=jdbc:mysql://localhost:3306/CLIMATE?zeroDateTimeBehavior=CONVERT_TO_NULL&serverTimezone=Europe/Berlin
spring.datasource.username=climateRUN
spring.datasource.password=climateRUN
spring.jpa.database-platform=org.hibernate.dialect.MySQL5Dialect
spring.datasource.initialization-mode=never
spring.datasource.schema=classpath:schema.sql
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.connection-timeout=99999999
spring.datasource.hikari.max-lifetime=99999999
spring.datasource.hikari.idle-timeout=9999999
#spring.data.jpa.repositories.enabled=false
spring.jpa.properties.hibernate.current_session_context_class=org.springframework.orm.hibernate5.SpringSessionContext
spring.task.execution.pool.keep-alive=6000s
spring.task.scheduling.pool.size=3
spring.batch.job.enabled=false
spring.batch.initialize-schema=never
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.type=trace
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
# Connection pool properties
#
connection.pool.initialPoolSize=5
connection.pool.minPoolSize=5
connection.pool.maxPoolSize=20
connection.pool.maxIdleTime=999999
##########################
# Set root logger level to DEBUG and its only appender to A1.
log4j.rootLogger=INFO, A1
# A1 is set to be a ConsoleAppender.
log4j.appender.A1=org.apache.log4j.ConsoleAppender
# A1 uses PatternLayout.
log4j.appender.A1.layout=org.apache.log4j.PatternLayout
log4j.appender.A1.layout.ConversionPattern=%-4r [%t] %-5p %c %x - %m%n
##########################
# logging level
logging.level.ch.studer=INFO
#logging.level.ch.studer=DEBUG
# output to a file
logging.file.name=climateAnalyser.log
logging.level.org.apache.tomcat=INFO
logging.level.org.apache.catalina=INFO
logging.file.path=.
logging.level.org.springframework=INFO
# temp folder example
#logging.file=${java.io.tmpdir}/app.log
#logging.pattern.file=%d %p %c{1.} [%t] %m%n
#logging.pattern.console=%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n
## if no active profile, default is 'default'
##spring.profiles.active=prod
# root level
#logging.level.=INFO
climate.path.unzipOutputFolderName=UnzipedDataInputDataFiles
climate.path.inputFolderName=InputFiles
climate.path.ftpDataFolderName=FTPData
climate.path.linuxFolderName=/tmp/ClimateAnalyzer
climate.path.windowsFolderName=C:\\temp\\ClimateAnalyzer
climate.ftp.server=opendata.dwd.de
climate.ftp.server.user=anonymous
climate.ftp.server.pwd=
climate.ftp.server.directory=climate_environment/CDC/observations_germany/climate/monthly/kl/historical/
# Defins the number of year for a ClimateService_OLD Period
climate.calculation.period.year=30
#Defines the range of years to calculate the average temperature ,to replace NULL_TEMPERATURE
climate.calculation.range.year=4
#Defines the NULL value for temperature as a BigDecimal type
climate.temperature.big.decimal.null.value=-999.0000
###################
spring.devtools.restart.exclude=OLDFTPData/**,InputFiles/**,UnzipedDataInputDataFiles/**
climate.path.temperature.input.file.pattern=produkt_
climate.path.temperature.input.file.type=.txt
climate.path.station.input.file.pattern=KL_Monatswerte_Beschreibung_Stationen
climate.path.station.input.file.type=.txt
© 2021 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
