name: Climate Analyser mvn build on push and automatic un- deployment

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
      - uses: actions/checkout@v1

      - name: Set up JDK 13
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 13

      - name: Build with Maven
        run: mvn -B package --file pom.xml
