name: Java CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 13
      uses: actions/setup-java@v1
      with:
        java-version: 13
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: undeployment
      run: curl "http://${{secrets.DEPLOY_USER}}@94.16.122.234:8080/manager/text/undeploy?path=/ClimateAnalyser"

    - name: deployment
      run: curl --upload-file /home/runner/work/climatedataanalyser/climatedataanalyser/climatedataanalyser-api/target/ClimateAnalyser.war "http://${{secrets.DEPLOY_USER}}@94.16.122.234:8080//manager/text/deploy?path=/ClimateAnalyser"
