name: Release

on:
  push:
    branches:
      - release


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Cache local Maven repository
        uses: actions/cache@v2.1.7
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Java JDK 11
        uses: actions/setup-java@v1.4.3
        with:
          java-version: 11
          server-id: github
      - name: Configure Git user
        run: |
          git config user.email "alex@alexstuder.com"
          git config user.name "Alexander Studer"
      - name: Publish JAR
        run: mvn -B release:prepare release:perform
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: undeployment
        run: curl "http://${{secrets.DEPLOY_USER}}@studer.tk:8080/manager/text/undeploy?path=/ClimateAnalyser"

      - name: deployment
        run: curl --upload-file /home/runner/work/climatedataanalyser/climatedataanalyser/climatedataanalyser-api/target/ClimateAnalyser.war "http://${{secrets.DEPLOY_USER}}@studer.tk:8080//manager/text/deploy?path=/ClimateAnalyser"

